# (C) Copyright Confidential Containers Contributors
# # SPDX-License-Identifier: Apache-2.0
#
# Run linting tools on the sources of the project.
---
name: lint
on: [workflow_dispatch, pull_request]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        go_version:
          - 1.19
    steps:
      - name: Checkout the pull request code
        uses: actions/checkout@v3
      - name: Setup Golang version ${{ matrix.go_version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libvirt-dev
      - name: Install golangci-lint
        env:
          GOLANGCI_LINT_VERSION: "1.52.2"
        working-directory: /tmp
        run: |
          curl -sSfLO "https://github.com/golangci/golangci-lint/releases/download/v${GOLANGCI_LINT_VERSION}/golangci-lint-${GOLANGCI_LINT_VERSION}-linux-amd64.tar.gz"
          tar -xzf "golangci-lint-${GOLANGCI_LINT_VERSION}-linux-amd64.tar.gz"
          sudo mv "golangci-lint-${GOLANGCI_LINT_VERSION}-linux-amd64/golangci-lint" /usr/local/bin
      - name: check
        run: make check
